import './globals.css'
import { Inter } from 'next/font/google'
import { clsx } from 'clsx'
import { HiChevronDown } from 'react-icons/hi'
import { MdDashboard } from 'react-icons/md'
import { BsBoxes, BsBoxSeamFill } from 'react-icons/bs'
import { AiFillHeart } from 'react-icons/ai'
import { TiStarburst } from 'react-icons/ti'
import Link from 'next/link'
import Image from 'next/image'
import { SearchField } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          inter.className,
          'min-h-screen bg-gray-200 flex flex-col'
        )}
      >
        <Navbar />
        <div className='flex flex-col gap-4 flex-1'>
          <div className='px-10 py-5 flex gap-4 flex-1'>
            <SideBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}

function Navbar () {
  return (
    <div className='px-4 md:px-16 py-4 flex items-center justify-between bg-white shadow'>
      <Link href='/'>
        <Logo />
      </Link>
      <div className='w-1/3'>
        <SearchField id='main-search' />
      </div>
      <div className='flex items-center gap-10'>
        <button className='flex items-center gap-1'>
          <CompactLogo />
          <HiChevronDown className='text-gray-500' />
        </button>
        <button className='flex gap-2 items-center justify-center'>
          <Image
            src={getRandomPersonImage()}
            alt='profile'
            height={35}
            width={35}
            className='rounded-full'
          />
          <div className='text-left'>
            <p className='font-semibold text-sm'>User Admin</p>
            <p className='text-xs text-gray-400'>useradmin@elred.com</p>
          </div>
          <HiChevronDown className='text-gray-500' />
        </button>
      </div>
    </div>
  )
}

function getRandomPersonImage () {
  return `https://randomuser.me/api/portraits/men/33.jpg`
}

function SideBar () {
  return (
    <div className='flex gap-8 flex-col rounded shadow bg-white p-2 w-56 py-10'>
      <div className='px-4 flex gap-3 items-center'>
        <CompactLogo />
        <span className='text-sm font-semibold'>A. T. Inks</span>
      </div>
      <div className='flex flex-col'>
        <NavLink href='#' icon={<MdDashboard />}>
          Dashboard
        </NavLink>
        <NavLink href='/products' icon={<BsBoxes />} isActive>
          All Products
        </NavLink>
        <NavLink href='#' icon={<BsBoxSeamFill />}>
          Orders
        </NavLink>
        <NavLink href='#' icon={<AiFillHeart />}>
          Favorites
        </NavLink>
        <NavLink href='#' icon={<TiStarburst />}>
          New Arrival
        </NavLink>
      </div>
    </div>
  )
}

function NavLink ({
  isActive = false,
  icon,
  children,
  href
}: {
  href: string
  isActive?: boolean
  icon: React.ReactNode
  children: React.ReactNode
}) {
  return (
    <Link
      className={clsx(
        'flex gap-4 items-center px-6 py-4 w-full rounded font-medium',
        isActive ? 'text-red-600' : 'text-gray-400',
        isActive && 'bg-red-50'
      )}
      href={href}
    >
      <span className='text-xl'>{icon}</span>
      <span className='text-xs'>{children}</span>
    </Link>
  )
}

function Logo () {
  return (
    <div className='font-bold'>
      <span className='text-sky-600'>A</span>.{' '}
      <span className='text-pink-600'>T</span>. Inks
    </div>
  )
}

function CompactLogo () {
  return (
    <div className='flex items-center justify-center h-10 w-10 rounded-full border-gray-300 border font-bold'>
      <span className='text-sky-600'>A</span>
      <span className='text-pink-600'>T</span>
    </div>
  )
}
